<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\FrontOne.Application\FrontOne.Application.csproj" />
    <ProjectReference Include="..\FrontOne.Infrastructure.SqlServer\FrontOne.Infrastructure.SqlServer.csproj" />
    <ProjectReference Include="..\FrontOne.Infrastructure.SapB1\FrontOne.Infrastructure.SapB1.csproj" />
    <ProjectReference Include="..\FrontOne.Shared\FrontOne.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="DevExpress.Win" Version="26.1.3" />
    <PackageReference Include="DevExpress.Win.Reporting" Version="26.1.3" />
    <PackageReference Include="GMap.NET.WindowsForms" Version="1.7.5" />
    <PackageReference Include="System.Data.SQLite.Core" Version="1.0.119" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.10" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="10.0.10" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.10" />
    <PackageReference Include="Serilog.Extensions.Logging" Version="10.0.0" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <None Update="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <None Remove="Resources\Mapas\PinHuerta.png" />
    <EmbeddedResource Include="Resources\Mapas\PinHuerta.png" />
  </ItemGroup>

</Project>