<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.4" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FrontOne.Domain\FrontOne.Domain.csproj" />
    <ProjectReference Include="..\FrontOne.Application\FrontOne.Application.csproj" />
    <ProjectReference Include="..\FrontOne.Shared\FrontOne.Shared.csproj" />
    <ProjectReference Include="..\FrontOne.Infrastructure.SqlServer\FrontOne.Infrastructure.SqlServer.csproj" />
    <ProjectReference Include="..\FrontOne.Infrastructure.SapB1\FrontOne.Infrastructure.SapB1.csproj" />
  </ItemGroup>

</Project>