USE FrontOne;
GO

SET QUOTED_IDENTIFIER ON;
GO

INSERT INTO Catalogos.Poblacion (Nombre, EstadoId, Activo)
SELECT v.Nombre, v.EstadoId, 1
FROM (VALUES
    (N'Acuitzio', 16),
    (N'Aguililla', 16),
    (N'Álvaro Obregón', 16),
    (N'Angamacutiro', 16),
    (N'Angangueo', 16),
    (N'Apatzingán', 16),
    (N'Aporo', 16),
    (N'Aquila', 16),
    (N'Ario', 16),
    (N'Arteaga', 16),
    (N'Briseñas', 16),
    (N'Buenavista', 16),
    (N'Carácuaro', 16),
    (N'Charapan', 16),
    (N'Charo', 16),
    (N'Chavinda', 16),
    (N'Cherán', 16),
    (N'Chilchota', 16),
    (N'Chinicuila', 16),
    (N'Chucándiro', 16),
    (N'Churintzio', 16),
    (N'Churumuco', 16),
    (N'Coahuayana', 16),
    (N'Coalcomán', 16),
    (N'Coeneo', 16),
    (N'Cojumatlán', 16),
    (N'Contepec', 16),
    (N'Copándaro', 16),
    (N'Cotija', 16),
    (N'Cuitzeo', 16),
    (N'Ecuandureo', 16),
    (N'Epitacio Huerta', 16),
    (N'Erongaricuaro', 16),
    (N'Gabriel Zamora', 16),
    (N'Hidalgo', 16),
    (N'La Huacana', 16),
    (N'Huandacareo', 16),
    (N'Huaniqueo', 16),
    (N'Huetamo', 16),
    (N'Huiramba', 16),
    (N'Indaparapeo', 16),
    (N'Irimbo', 16),
    (N'Ixtlán', 16),
    (N'Jacona', 16),
    (N'Jiménez', 16),
    (N'Jiquilpan', 16),
    (N'José Sixto Verduzco', 16),
    (N'Juárez', 16),
    (N'Jungapeo', 16),
    (N'Lagunillas', 16),
    (N'La Piedad', 16),
    (N'Lázaro Cárdenas', 16),
    (N'Los Reyes', 16),
    (N'Madero', 16),
    (N'Maravatío', 16),
    (N'Marcos Castellanos', 16),
    (N'Morelia', 16),
    (N'Morelos', 16),
    (N'Múgica', 16),
    (N'Nahuatzen', 16),
    (N'Nocupétaro', 16),
    (N'Nuevo Parangaricutiro', 16),
    (N'Nuevo Urecho', 16),
    (N'Numarán', 16),
    (N'Ocampo', 16),
    (N'Pajacuarán', 16),
    (N'Panindicuaro', 16),
    (N'Paracho', 16),
    (N'Parácuaro', 16),
    (N'Pátzcuaro', 16),
    (N'Penjamillo', 16),
    (N'Peribán', 16),
    (N'Purépero', 16),
    (N'Puruándiro', 16),
    (N'Queréndaro', 16),
    (N'Quiroga', 16),
    (N'Sahuayo', 16),
    (N'Salvador Escalante', 16),
    (N'San Lucas', 16),
    (N'Santa Ana Maya', 16),
    (N'Senguio', 16),
    (N'Susupuato', 16),
    (N'Tacámbaro', 16),
    (N'Tancítaro', 16),
    (N'Tangamandapio', 16),
    (N'Tangancícuaro', 16),
    (N'Tanhuato', 16),
    (N'Taretan', 16),
    (N'Tarímbaro', 16),
    (N'Tepalcatepec', 16),
    (N'Tingambato', 16),
    (N'Tingüindín', 16),
    (N'Tiquicheo de Nicolás Romero', 16),
    (N'Tlalpujahua', 16),
    (N'Tlazazalca', 16),
    (N'Tocumbo', 16),
    (N'Tumbiscatío', 16),
    (N'Turicato', 16),
    (N'Tuxpan', 16),
    (N'Tuzantla', 16),
    (N'Tzintzuntzan', 16),
    (N'Tzitzio', 16),
    (N'Uruapan', 16),
    (N'Venustiano Carranza', 16),
    (N'Villamar', 16),
    (N'Vista Hermosa', 16),
    (N'Yurécuaro', 16),
    (N'Zacapu', 16),
    (N'Zamora', 16),
    (N'Zináparo', 16),
    (N'Zinapécuaro', 16),
    (N'Ziracuaretiro', 16),
    (N'Zitácuaro', 16),
    (N'Acatic', 14),
    (N'Acatlán', 14),
    (N'Ahualulco', 14),
    (N'Amacueca', 14),
    (N'Amatitán', 14),
    (N'Ameca', 14),
    (N'Arandas', 14),
    (N'Atemajac de Brizuela', 14),
    (N'Atengo', 14),
    (N'Atenguillo', 14),
    (N'Atotonilco El Alto', 14),
    (N'Atoyac', 14),
    (N'Autlán', 14),
    (N'Ayotlán', 14),
    (N'Ayutla', 14),
    (N'Bolaños', 14),
    (N'Cabo Corrientes', 14),
    (N'Cañadas', 14),
    (N'Casimiro Castillo', 14),
    (N'Chapala', 14),
    (N'Chimaltitán', 14),
    (N'Chiquilistlán', 14),
    (N'Cihuatlán', 14),
    (N'Cocula', 14),
    (N'Colotlán', 14),
    (N'Concepción de Buenos Aires', 14),
    (N'Cuautitlán', 14),
    (N'Cuautla', 14),
    (N'Cuquío', 14),
    (N'Degollado', 14),
    (N'Ejutla', 14),
    (N'El Arenal', 14),
    (N'El Grullo', 14),
    (N'El Limón', 14),
    (N'El Salto', 14),
    (N'Encarnación', 14),
    (N'Etzatlán', 14),
    (N'Gómez Farías', 14),
    (N'Guachinango', 14),
    (N'Guadalajara', 14),
    (N'Hostotipaquillo', 14),
    (N'Huejúcar', 14),
    (N'Huejuquilla El Alto', 14),
    (N'Ixtlahuacán de los Membrillos', 14),
    (N'Ixtlahuacan del Río', 14),
    (N'Jalostotitlán', 14),
    (N'Jamay', 14),
    (N'Jesús María', 14),
    (N'Jilotlán de los Dolores', 14),
    (N'Jocotepec', 14),
    (N'Juanacatlán', 14),
    (N'Juchitlán', 14),
    (N'La Barca', 14),
    (N'La Huerta', 14),
    (N'La Manzanilla de La Paz', 14),
    (N'Lagos de Moreno', 14),
    (N'Magdalena', 14),
    (N'Mascota', 14),
    (N'Mazamitla', 14),
    (N'Mexticacán', 14),
    (N'Mezquitic', 14),
    (N'Mixtlán', 14),
    (N'Ocotlán', 14),
    (N'Ojuelos', 14),
    (N'Píhuamo', 14),
    (N'Poncitlán', 14),
    (N'Puerto Vallarta', 14),
    (N'Quitupan', 14),
    (N'San Cristobal de la Barranca', 14),
    (N'San Diego de Alejandría', 14),
    (N'San Gabriel', 14),
    (N'San Ignacio Cerro Gordo', 14),
    (N'San Juan de los Lagos', 14),
    (N'San Juanito de Escobedo', 14),
    (N'San Julián', 14),
    (N'San Marcos', 14),
    (N'San Martín de Bolaños', 14),
    (N'San Martín Hidalgo', 14),
    (N'San Miguel El Alto', 14),
    (N'San Sebastián del Oeste', 14),
    (N'Santa María de los Angeles', 14),
    (N'Santa María del Oro', 14),
    (N'Sayula', 14),
    (N'Tala', 14),
    (N'Talpa', 14),
    (N'Tamazula', 14),
    (N'Tapalpa', 14),
    (N'Tecalitlán', 14),
    (N'Techaluta', 14),
    (N'Tecolotlán', 14),
    (N'Tenamaxtlán', 14),
    (N'Teocaltiche', 14),
    (N'Teocuitatlán', 14),
    (N'Tepatitlán', 14),
    (N'Tequila', 14),
    (N'Teuchitlán', 14),
    (N'Tizapan El Alto', 14),
    (N'Tlajomulco', 14),
    (N'Tlaquepaque', 14),
    (N'Tolimán', 14),
    (N'Tomatlán', 14),
    (N'Tonalá', 14),
    (N'Tonaya', 14),
    (N'Tonila', 14),
    (N'Totatiche', 14),
    (N'Tototlán', 14),
    (N'Tuxcacuesco', 14),
    (N'Tuxcueca', 14),
    (N'Tuxpan', 14),
    (N'Unión de San Antonio', 14),
    (N'Unión de Tula', 14),
    (N'Valle de Guadalupe', 14),
    (N'Valle de Juárez', 14),
    (N'Villa Corona', 14),
    (N'Villa Guerrero', 14),
    (N'Villa Hidalgo', 14),
    (N'Villa Purificación', 14),
    (N'Yahualica', 14),
    (N'Zacoalco', 14),
    (N'Zapopan', 14),
    (N'Zapotiltic', 14),
    (N'Zapotitlán', 14),
    (N'Zapotlán del Rey', 14),
    (N'Zapotlán el Grande', 14),
    (N'Zapotlanejo', 14)
) AS v(Nombre, EstadoId)
WHERE NOT EXISTS (
    SELECT 1 FROM Catalogos.Poblacion p WHERE p.Nombre = v.Nombre AND p.EstadoId = v.EstadoId
);
GO
